### ISSUE TITLE
python.jpeg missing from source tarball

### ISSUE THREAD

**Issue by stefanor** [jwilk/python-aalib#1]
Add a MANIFEST.in entry?

**Comment by jwilk** [comment]
D'oh!
Fixed in a6b64e3e2a1f3a2319160c8a407735b308f042ad.
I'll make a new release in a few hours.

**Comment by jwilk** [comment]
> Fixed in a6b64e3e2a1f3a2319160c8a407735b308f042ad.

More precisely, in b26e9958f1db3079bf6dfa1ef5664a2b9c7841ad.

**Comment by jwilk** [comment]
Fixed in 0.3.2.
