### ISSUE TITLE
Structs are only packed on i386

### ISSUE THREAD

**Issue by stefanor** [jwilk/python-aalib#4]
Debian bug: https://bugs.debian.org/982553

> Dear Maintainer,
>
> It looks like there's an ABI mismatch between the structure layout declared in the python code and the actual layout.
>
> It causes python to allocate less memory than needed by the C library. On rare occasions, the uninitialized field gets a non-zero value, which produce weird behaviors.
> 
> Specifically, the struct fields of `aa_hardware_params` and `aa_render_params` are only aligned on 4 bytes on i386 when compiled with gcc. Not on x64 or any other architecture as far as I can tell.
>
> When reading the beginning of aalib.h we can see:
> 
> ```
> /* The -malign-double switch changes binarry compatibility with structures
>    containing floating point values.  To avoid this, set alignment manually
>    to old value.  */
> 
> #ifdef __GNUC__
> #ifdef __i386__
> #define __AA_ALIGN __attribute__ ((__aligned__ (4)))
> #define __AA_NOALIGN __attribute__ ((__packed__))
> #endif
> #endif
> ```
>
> Which shows explicitely that the struct fields are only aligned or packed on i386. Given the specificity of the condition and the comment above, my guess would be that this was made only to prevent an ABI breakage when upgrading gcc, and not a general definition.
> 
> Therefore I think that the `_pack_ = 4` attribute when declaring the structures is too strict.
>
> ``` 
> class HardwareSettings(Structure):
>     _pack_ = 4
>     _fields_ = [
>         # ...
>     ]
> ```
>
> Although I have no clue how to detect it, this should probably be set only for the 32 bits builds on intel-compatible platforms (only when `__i386__` is set). Note that 32 bits systems can be installed on 64 bits hardware, and 32 bits builds of python can be installed in 64 bits debian systems. So it should really be the `ELFCLASS` of the library that should be tested, neither the architecture of the hardware nor the debian arch.
> 
> On the other hand, maybe an easier fix would be to have a more consistent ABI on the aalib side? Although this would mean bumping the ABI version and possibly breaking many packaged, this might be the best long-term solution. If you think so, feel free to reassign this bug report as needed.
>
> Best regards,
> Celelibi

Looks correct to me. Sounds like you should be only be setting `_pack_` if `platform.machine() in ('i386', 'i686', 'x86_64') and ctypes.sizeof(ctypes.c_void_p) == 4` or something like that.

**Comment by jwilk** [comment]
>> It looks like there's an ABI mismatch between the structure layout declared in the python code and the actual layout.

Oops…

> Sounds like you should be only be setting `_pack_` if `platform.machine() in ('i386', 'i686', 'x86_64') and ctypes.sizeof(ctypes.c_void_p) == 4` or something like that.

This doesn't do the right thing on x32, which has 4-bytes pointers, but aligns doubles at 8 bytes.

I'm tempted to just drop `_pack_` completely, which should do the right thing as long as the interpreter wasn't built with `-malign-double`.

**Comment by jwilk** [comment]
> I'm tempted to just drop `_pack_` completely

I've done that in 47400801ca63fbcb787da4b53f5880fbe455f420.
I've also added some ABI checking tests in a3b5d551edffa8aac39848fbeb0de0a9e5e97dd0.

I intend to make a new release in a few days.

**Comment by jwilk** [comment]
Fixed in [0.4](https://pypi.org/project/python-aalib/0.4/).
